language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r test_requirements.txt"
services: redis-server
# command to run tests
script: bash runtests.sh